/**
 * PROJECT EULER : PROBLEM 2
 * @author Mads Heckmann
 * 
 *	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem002
{
	public static void main(String[] args)
	{
		int x = 0, y = 1, z = 0, sum = 0;
		do
		{
			z = x + y;
			x = y;
			y = z;
			
			if (y % 2 == 0)
			{
				sum += y;
			}
		}
		while (y <= 4000000);
		System.out.println("Value of terms in Fib-sequence whose values does not exceed 4 000 000: " + sum);
	}
}